# -*- coding: utf-8 -*-
"""lists.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s_OFRoh30u8sWva_nZxysJ_em5PaTqmX

#LISTS
"""

users = ['val', 'bob', 'mia', 'ron', 'ned']

users[0]

users[-1]

users = ['val', 'bob', 'mia', 'ron', 'ned','need','chjsbsac']

users[-1]

first_user = users[0]

first_user

second_user = users[1]

second_user

newest_user = users[-1]

newest_user

users[0] = 'valerie'
users[-2] = 'ronald'

users

users.append('amy')

users

users = []
users.append('val')
users.append('bob')
users.append('mia')

users

users = []
users.append('val')
users.append('bob')
users.append('mia')
users.append('sid')

users

users.insert(0, 'joe')
users.insert(3, 'bea')

users

users.insert(5,'aru')

users

del users[-1]

users

users.remove('mia')

users

users.append('mia')

users

users.remove('mia')

users

most_recent_user = users.pop()
print(most_recent_user)

most_recent_user = users.pop()
print(most_recent_user)

users

first_user = users.pop(0)
print(first_user)

users

users.append('val')
users.append('bob')
users.append('mia')
users.append('sid')

users

first_user = users.pop(1)
print(first_user)

len(users)

num_users = len(users)
print("We have " + str(num_users) + " users.")

users.sort()

users

users.sort(reverse=True)

users

print(sorted(users))
print(sorted(users, reverse=True))

users.append('val')
users.append('bob')
users.append('mia')
users.append('sid')

users

print(sorted(users))
print(sorted(users,reverse=True))

user

user

users = ['val', 'bob', 'mia', 'ron', 'ned']

for user in users:
  print(user)

users.append('sid')

users

for user in users:
  print(user)

for user in users:
  print("Welcome, " + user + "!")
print("Welcome, we're glad to see you all!")

users = ['hlo','hi','bye','sid','loki','de']
for user in users:
  print("plz, welcome " +  user  + "! ")
print("welocme!, all of u")

for number in range(11):
  print(number)

range(10)

for number in range(1, 11):
  print(number)

ages = [93, 99, 66, 17, 85, 1, 35, 82, 2, 77]
youngest = min(ages)

youngest

ages = [93, 99, 66, 17, 85, 1, 35, 82, 2, 77]
oldest = max(ages)

oldest

ages = [93, 99, 66, 17, 85, 1, 35, 82, 2, 77]
print(sum(ages))

ages = [93, 99, 66, 17, 85, 1, 35, 82, 2, 77]
total_years = sum(ages)
total_years

finishers = ['kai', 'abe', 'ada', 'gus', 'zoe']
first_three = finishers[:3]
first_three

middle_three = finishers[1:4]
middle_three

last_three = finishers[-3:]
last_three

finishers = ['kai', 'abe', 'ada', 'gus', 'zoe']
copy_of_finishers = finishers[:]
copy_of_finishers

finishers = ['kai', 'abe', 'ada', 'gus', 'zoe']
copy_of_finishers = finishers[:4]

copy_of_finishers

squares = []
for x in range(1, 11):
  square = x**2
  squares.append(square)
squares

squares =[x**3 for x in range(1,11)]
squares

names = ['kai', 'abe', 'ada', 'gus', 'zoe']
upper_names = []
for name in names:
  upper_names.append(name.upper())

upper_names

names = ['kai', 'abe', 'ada', 'gus', 'zoe']
upper_names = [name.upper() for name in names]
upper_names

dimensions = (800, 600)

